# Generated by Django 4.2.30 on 2026-09-27 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('link', 'Link')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.contest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('pitch', models.TextField(blank=True, help_text='What the company will make (YC-style)')),
                ('product', models.TextField(blank=True, help_text='What the company will make')),
                ('whats_new', models.TextField(blank=True, help_text="What's new / substitutes")),
                ('competitors', models.TextField(blank=True)),
                ('insight', models.TextField(blank=True, help_text="What you understand that others don't")),
                ('outcome', models.CharField(choices=[('successful', 'Funded by YC'), ('unsuccessful', 'Rejected by YC'), ('pending', 'Undecided')], default='pending', max_length=12)),
                ('batch', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(choices=[('human', 'Human founder'), ('ai', 'AI agent')], default='human', max_length=10)),
                ('model_name', models.CharField(blank=True, help_text='If source=ai: e.g. chatgpt, claude, muse-spark-1.3, glm-5.3', max_length=100)),
                ('founders_blurb', models.CharField(blank=True, max_length=500)),
                ('is_public', models.BooleanField(default=True, help_text='False = private rating: rated vs anchors but hidden from leaderboard + fetch API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.contest')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_image', models.ImageField(blank=True, null=True, upload_to='submission_images/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.contestfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tie', models.BooleanField(default=False)),
                ('judge', models.CharField(default='heuristic-v1', max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.contest')),
                ('submission_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='core.submission')),
                ('submission_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='core.submission')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='core.submission')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EloRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1500)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('ties', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.contest')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elo', to='core.submission')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
